version: '3.8'

x-shared:
  &common
  NEO4J_AUTH: neo4j/testtest
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_PLUGINS: '["apoc"]'
  NEO4J_dbms_security_allow__csv__import__from__file__urls: "true"
  NEO4J_dbms_security_auth__minimum__password__length: 4
  EXTENDED_CONF: 'yes'

x-shared-cluster:
  &common-cluster
  <<: *common
  NEO4J_EDITION: 'enterprise'

x-shared-core:
  &common-core
  <<: *common-cluster
  NEO4J_initial_server_mode__constraint: 'PRIMARY'

networks:
    neo4j:
        driver: bridge

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /opt/project
        networks:
            - neo4j
        volumes:
            - .:/opt/project
        expose:
            - 9000
        env_file:
          - .env
    testkit-backend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - WITH_XDEBUG=true
        working_dir: /opt/project
        volumes:
            - .:/opt/project
        command: php /opt/project/testkit-backend/index.php
        networks:
          - neo4j
        depends_on:
          - neo4j
        ports:
          - "9876:9876"
    neo4j:
        networks:
            - neo4j
        image: neo4j:5
        healthcheck:
          test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
        user: ${USER_ID}:${GROUP_ID}
        ports:
          - "7687:7687"
          - "7474:7474"
        environment:
          <<: *common
        volumes:
          - ./tests/resources:/import
          - ./neo4j.conf:/conf/neo4j.conf
        env_file:
          - .env
    core1:
        image: neo4j:5
        healthcheck:
          test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
        user: ${USER_ID}:${GROUP_ID}
        networks:
            - neo4j
        volumes:
          - ./tests/resources:/import
          - ./neo4j.conf:/conf/neo4j.conf
        environment:
          <<: *common-core
        env_file:
          - .env

    core2:
        image: neo4j:5
        healthcheck:
          test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
        user: ${USER_ID}:${GROUP_ID}
        networks:
            - neo4j
        environment:
          <<: *common-core
        volumes:
          - ./tests/resources:/import
          - ./neo4j.conf:/conf/neo4j.conf
        env_file:
          - .env

    core3:
        image: neo4j:5
        healthcheck:
          test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
        user: ${USER_ID}:${GROUP_ID}
        networks:
            - neo4j
        environment:
          <<: *common-core
        volumes:
          - ./tests/resources:/import
          - ./neo4j.conf:/conf/neo4j.conf
        env_file:
          - .env

    readreplica1:
        image: neo4j:5
        healthcheck:
          test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
        user: ${USER_ID}:${GROUP_ID}
        networks:
            - neo4j
        environment:
          <<: *common-cluster
          NEO4J_initial_server_mode__constraint: SECONDARY
        env_file:
          - .env
        volumes:
          - ./tests/resources:/import
          - ./neo4j.conf:/conf/neo4j.conf
