name: Unit Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest
    name: "Running Unit tests for PHP ${{ matrix.php-version }}"
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1']

    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: ${{ matrix.php-version }}
          version: 2
      - name: Run unit tests
        run: php vendor/bin/phpunit --testsuite Unit
